use_frameworks!

platform :ios, '8.0'

target 'HqxModule_Example' do
  pod 'HqxModule', :path => '../'

  target 'HqxModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
